services:
  - type: web
    name: complaintracker-ml
    runtime: python
    plan: free
    rootDir: ml_engine
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: web
    name: complaintracker-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && node seed.js
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemma-3-27b-it
      - key: ML_ENGINE_URL
        fromService:
          type: web
          name: complaintracker-ml
          property: hostport
